### ISSUE TITLE
Character PR todo

### ISSUE THREAD

**Issue by fmatthew5876** [fmatthew5876/Player#2]
- [ ] Check all fixmes
- [ ] Change Graphic move route
- [ ] Set Transparency - embed clamp in code
- [ ] Test jumps w/o end - chunks
